language: python

python:
  - "3.7"
  - "3.6"
  - "3.5"

branches:
  only:
    - master

install:
  - pip install -r requirements-test.txt
  - pip install codecov
  - python setup.py -q develop

script:
  - PYTHONPATH=$PYTHONPATH:. mamba --enable-coverage

after_success:
  - codecov